### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by hudochenkov** [webschik/postcss-less#9]
I've trying to test this parser, but it doesn't work. PostCSS doesn't understand it:

```
$ node index.js
/Users/aleks/projects/postcss-less-bug/node_modules/postcss/lib/lazy-result.js:58
            if (parser.parse) parser = parser.parse;
                      ^

TypeError: Cannot read property 'parse' of undefined
    at new LazyResult (/Users/aleks/projects/postcss-less-bug/node_modules/postcss/lib/lazy-result.js:58:23)
    at Processor.process (/Users/aleks/projects/postcss-less-bug/node_modules/postcss/lib/processor.js:34:16)
    at Object.<anonymous> (/Users/aleks/projects/postcss-less-bug/index.js:5:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

I've created test case for this: https://github.com/hudochenkov/postcss-less-bug

**Comment by webschik** [comment]
@hudochenkov , if you are not using ES2015 + Babel.js, please use `require('postcss-less').default`.
https://phabricator.babeljs.io/T2212

**Comment by hudochenkov** [comment]
All other PostCSS syntaxes working like `require('postcss-less')`. Why your syntax should be different from other syntaxes? This will confuse developers who would use your parser.

**Comment by webschik** [comment]
Yep, make sense. I'm going to fix it asap.

**Comment by webschik** [comment]
@hudochenkov , it's fixed ;)

**Comment by hudochenkov** [comment]
Thank you!
